id: cj0a0xcni0000386wfad6dbqr
gist: ''
host: WEB
api_set: {}
platform: null
created_at: 1489525334147
modified_at: 1489525406093
origin: 'https://bornholm-edge.azurewebsites.net'
author: Microsoft
name: Blank snippet
description: Create a new snippet from a blank template.
script:
  content: |
    $("#run").click(run);

    function run() {
        console.log("Your code goes here");
    }
  language: typescript
style:
  content: "/* Your style goes here */\r\n"
  language: css
template:
  content: |
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
libraries: |
  # CSS Libraries
  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css

  # NPM libraries
  core-js@2.4.1/client/core.min.js
  @microsoft/office-js-helpers@.5.0/dist/office.helpers.min.js
  jquery@3.1.1

  # IntelliSense: @types/library or node_modules paths or URL to d.ts files
  @types/core-js
  @microsoft/office-js-helpers/dist/office.helpers.d.ts
  @types/jquery
