id: cixuvs3u200004q71uuen8333
gist: d1cb7df01dabb66b046cd2c7881248e4
source: ''
author: Microsoft
name: Blank Excel snippet
description: Create a new Excel snippet from a blank template.
script:
  content: |-
    $('#run').click(function () {
        invokeRun().catch(OfficeHelpers.Utilities.log);
    });

    function invokeRun() {
        await Excel.run(async (context) => {
            var range = context.workbook.getSelectedRange();
            range.format.fill.color = 'yellow';
            await context.sync();
        });
    }
  language: typescript
style:
  content: |-
    body {
        margin: 0;
        padding: 10px;
    }


    /* Button customization, including overwriting some Fabric defaults */

    .ms-Button, .ms-Button:focus {
        background: #217346;
        border: #217346;
    }

        .ms-Button > .ms-Button-label,
        .ms-Button:focus > .ms-Button-label,
        .ms-Button:hover > .ms-Button-label {
            color: white;
        }

        .ms-Button:hover, .ms-Button:active {
            background: #164b2e;
        }

        .ms-Button.is-disabled, .ms-Button:disabled {
            background-color: #f4f4f4;
            border-color: #f4f4f4;
        }

        .ms-Button.is-disabled .ms-Button-label,
        .ms-Button:disabled .ms-Button-label {
            color: #a6a6a6;
        }
  language: css
template:
  content: |-
    <p class="ms-font-m">Executes a simple code snippet</p>
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run code</span>
    </button>
  language: html
libraries: >-
  // Office.js CDN reference

  https://appsforoffice.microsoft.com/lib/1/hosted/Office.js


  // References to other NPM libraries

  jquery

  office-ui-fabric-js/dist/js/fabric.min.js

  office-ui-fabric-js/dist/css/fabric.min.css

  office-ui-fabric-js/dist/css/fabric.components.min.css

  @microsoft/office-js-helpers/dist/office.helpers.min.js

  core-js/client/core.min.js


  // IntelliSense definitions

  // Syntax: "dt~library_name" for DefinitelyTyped, or raw URLs to d.ts
  locations

  dt~office-js

  dt~jquery

  dt~core-js

  @microsoft/office-js-helpers/dist/office.helpers.d.ts
